# Uncomment this line to define a global platform for your project
# platform :ios, '9.0'

source 'http://gitlab.mrd.sohuno.com/haixuwu/pnmediator.git'
source 'https://github.com/CocoaPods/Specs.git'

use_frameworks!

target '__ProjectName__' do
 
end
